### PR TITLE
Add EuroLinux distribution

### PR DESCRIPTION
**Pull request by jakub-olczyk**
Hi!

This PR is complementary to issue #134. I thought I'd help out since it isn't much work to compile `gnuclad` and make the changes myself ;)

I tried to follow as best as I could the structure in the `gldt.csv` so I hope that it looks ok.

Disclaimer: I work with the company that created the distro & I have a little bit of inside knowledge when it comes to release date.

Cheers!

### CODE REVIEW

**Comment by jakub-olczyk** [comment]
Hey!

The patch has been rebased with the newest release in mind.

Cheers!

**Comment by FabioLolix** [comment]
Do you mind update the url to https://fabiololix.gitlab.io/os/linux/e/eurolinux/ ?

There is also a color change for DNALinux, it has been made inadvertently?

> The patch has been rebased with the newest release in mind.

Thanks, while in the past I have bothered people for that is no longer necessary as I've discovered I can do it myself from my side of github

**Comment by jakub-olczyk** [comment]
Hi @FabioLolix,

I think it will be best to follow PR #215. I'll close this one as suggested in the discussion there.

Cheers!

**Comment by FabioLolix** [comment]
Ok

**Pull request closed without merging**
