### PR TITLE
discontinued antergos, added endeavour

### LINKED ISSUE #79: Discontinuation of Antergos.
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name:

* Base:

* Start date:

* (eventual) Name changes with date: 

* URL:

* (optional) Color in hex:

* (optional) Description and history: talk about the project, for adding to distributions.md

**Discontinuing a distribution**

* Name: Antergos

* Stop date: 21/05/2019

* Statement URL (if any): https://antergos.com/blog/antergos-linux-project-ends/

### LINKED ISSUE #85: antergos discontinued, endeavour os released
*NOTE: If the issue is NOT about adding/discontinuing a distro, delete these out.*

**Adding a distribution**

* Name: Endeavour OS

* Base: Arch

* Start date: 15.07.2019 (i think)

* (eventual) Name changes with date: 

* URL: https://endeavouros.com/

* (optional) Color in hex: #7f3fbf

* (optional) Description and history: talk about the project, for adding to distributions.md
easy installable arch (like antergos, now discontinued) for distrohoppers, comes with xfce but might get a net installer like antergos where you can choose your desktopn environment. some developers went from antergos directly to endeavour
(https://itsfoss.com/endeavouros/)

**Discontinuing a distribution**

* Name: Antergos

* Stop date:21.05.2019 (i think)

* Statement URL (if any):https://antergos.com/blog/antergos-linux-project-ends/

### PR DESCRIPTION
**Pull request by Adrijaned**
fix #85 
fix #79 
replaces #80 with its messy git history

### CODE REVIEW

**Comment by FabioLolix** [comment]
Hello @Adrijaned and thank you for your patience

I have just commented on #80 

Unfortunately I will not merge this because Endeavour OS is still too young (I will not add distros that have less then 2/2.5 years) and still had amatourish builded packages last time I have checked; there has been some improvement like GPG singing (I know best Arch packaging and for the timeline I'm doing an effort to add quality distros, it is a thing I have thinked on in the last 6+ months)

**Comment by markusstraub** [comment]
Endeavour OS is now around for more than 2 years and quite popular according to distrowatch. Maybe you could reconsider adding it?

**Comment by FabioLolix** [comment]
Hello @markusstraub 

> Endeavour OS is now around for more than 2 years

I don't add projects that have less then 2,5 years (some exception could be made for commercially baked projects)

> quite popular according to distrowatch

I'm not taking in consideration DistroWatch Page Hit Ranking

> Maybe you could reconsider adding it?

No, they still lacks very basics of packaging

[Timeline direction](https://github.com/FabioLolix/LinuxTimeline/issues/158)

**Comment by NoEnd-yt** [comment]
Is it mature enough now?

> No, they still lacks very basics of packaging

Also, what do you mean by that?

**Comment by FabioLolix** [comment]
@NoEnd-yt 

> It’s been around for around 4 years. Is it mature enough now?

Haven't looked at it in the last year or more (and it is not only a question of age)


>     No, they still lacks very basics of packaging
> 
> Also, what do you mean by that?

Generally speaking; Arch packaging is very flexible, you can make a package that don't follow a lot of rules and guidelines and that more or less work (or work under certain conditions), and I have some experience on it, also packages that don't  have a packager field, are not GPG signed and aren't build in clean chroot are an indicator of quality (or lack thereof)

**Comment by Root-Core** [comment]
@FabioLolix So you seem to be very opinionated about the quality of some distributions, but are you sure all or even most of the distros on the timeline would meet your personal criteria of relevancy? Isn't this project about the history / timeline of Linux? Preference or even (perceived) quality should not be a concern here.. Endeavour is more popular and longer around than other distributions listed. Same is true for Garuda Linux #149.

I totally understand that short running distros aren't added or are removed at a later point, but this is not the case here. (While I would prefer a more complete approach, but this would be insane in the Linux world.)

PS: I really like this project, thank you!

**Comment by FabioLolix** [comment]
> So you seem to be very opinionated about the quality of some distributions

All the distro; not only some.

> are you sure all or even most of the distros on the timeline would meet your personal criteria of relevancy? Isn't this project about the history / timeline of Linux? Preference or even (perceived) quality should not be a concern here.

Quality; not relevancy. I have inherited the timeline; I haven't made it from scratch.

About quality there is a lot say and there a lot of sub-optimal stuff out there (do you consider out-of-repository packages good? No public buildfiles for packages is good? Dirty building packages with missing dependencies is good? No public build iso scripts (or equivalent) is good?)

Since I'm not completely happy with several 'legacy' additions (even some of my own) and I didn't want to 'denaturalize' the thing I have made a new timeline from scratch, so I can lax some rules here (having a quite good page on my distroware will remain) to address this type of concerns.

Garuda and Endeavour have about 3.5 years the oldest, is not that much overall.
You're welcome to help gather informations on distros you like https://distroware.gitlab.io/contributing/fullfilling/

> I totally understand that short running distros aren't added or are removed at a later point

I made 2,5 years of lifespan and at least 4 release the entry point, seems reasonable to me, also this isn't the only thing I work on (+full time job) and another thing have the precedence

> PS: I really like this project, thank you!

I'm glad you like it :)

**Comment by jiangzhenjerry** [comment]
In the next release is it possible to reconsider your decision to exclude EndeavourOS? It's 6 years old, and you have several younger distros on the chart already. With all due respect, excluding a distro that's been consistently top 5 in HPD on distrowatch over the past 4 years and has an average rating of 8.5 just seems a little... biased.

**Comment by FabioLolix** [comment]
> In the next release is it possible to reconsider your decision to exclude EndeavourOS?

 You're welcome to help gather informations on distros you like https://distroware.gitlab.io/contributing/fullfilling/

It is like a running joke

**Pull request closed without merging**
