### PR TITLE
Adding Rocky Linux

### PR DESCRIPTION
**Pull request by JohnCMoon**
Adding Rocky per issue #185.

### CODE REVIEW

**Comment by OkayPJ** [comment]
According to [Rocky Linux 8.3 RC1 Available Now](https://rockylinux.org/news/rocky-linux-8-3-rc1-release/), their first version was released in 2021-04-30, and [the initial commit of their GitHub repo](https://github.com/rocky-linux/rocky/commit/1958b6bba2ab2b63b286599959769504ff7229cf) is in 2020-12-09. So I don't think 2021-6 should be the starting date.

**Comment by JohnCMoon** [comment]
Understood - I was looking at the first non-candidate release. Will update to the first RC (I think it's hard to say from their Git history when the "code" for the distro was released).

**Comment by FabioLolix** [comment]
Hello and thanks for your patience,

> Adding Rocky per issue #185.

That was a placeholder for saying that I'm aware of it :)

Lately I'm not adding young distros anymore, who make directly a PR will not see the templates, and the PR template that I added later don't work.

For starting date use the date of the first public release (precise to the day)

For the URL use https://fabiololix.gitlab.io/os/linux/r/rockylinux.md

The page code can be found here: https://github.com/FabioLolix/fabiololix.gitlab.io/blob/master/docs/os/linux/r/rockylinux.md

For the screenshot don't need to provide them as haven't worked on them yet.

The chart need to be filled a bit and I need build instructions for the ISO

**Comment by FabioLolix** [comment]
Would you like to rebase and use 2021-04-30 as start date?

**Pull request merged**
