### PR TITLE
Some EOL Distros

### PR DESCRIPTION
**Pull request by jorgenatz**
Add end dates for distros based on information:

Parsix: https://web.archive.org/web/20180121014349/http://parsix.org:80/wiki/News

Semplice: https://web.archive.org/web/20171230092342/http://semplice-linux.org:80/blog/2015/09/semplice-for-workstations-2015.2-released (more than one year since last stable release, and website down)

Burapha: https://web.archive.org/web/20141219033514/https://buraphalinux.org/

Caixa Magica: http://linux.caixamagica.pt/pag/f_notc00.php?id=288
http://linux.caixamagica.pt/pag/f_notc00.php?id=287

JOPUX: https://sourceforge.net/projects/jopux

Turbolinux: http://www.turbolinux.com/support/lifecycle.html (no forums, more than 3 years after last stable release)

Fusion Linux: https://distrowatch.com/table.php?distribution=fusion
https://www.facebook.com/FusionLinux (last release 2011, last post 2013)

Synergy Linux: https://web.archive.org/web/20120710105236/http://synergy-linux.com:80/

K12Linux: https://web.archive.org/web/20161228071255/https://fedorahosted.org/k12linux/

Sonar: https://web.archive.org/web/20170611165634/http://sonargnulinux.com:80/index.php/2016/03/02/sonar-2016-3-is-out/

Simplicity: https://web.archive.org/web/20170829004726/http://simplicitylinux.org:80/

Devil: http://www.devil-linux.org/news/index.php?item=2009

Jarro Negro: https://www.facebook.com/Jarro-Negro-227310427375546/
http://jarronegrolinux.com/jn_proyecto.php

Openmamba: https://openmamba.org/en/blog/2017/01/05/openmamba-end-of-life-announcement/

### CODE REVIEW

**Comment by FabioLolix** [comment]
That's a lot of things :)

Don't have time till the weekend

Thanks for digging distributions

**Comment by FabioLolix** [comment]
For convention set 3 years after the latest release if there aren't statement



please use double digits for months 


* Parsix: OK

* Semplice: too early, website at http://semplice-linux.sourceforge.net/

* Burapha: OK

* Caixa Magica: OK

* JOPUX: blacklisted for lack of everything

* Turbolinux: where does come from that stop date?

* Fusion: 2011-07-02 + 3 years

* Synergy: June 26, 2012 + 3 years

* K12: why 2014.3.17 ? last release according to Distrowatch was on 2009-02-04

* Sonar: "too early". I'm investigating about it

* Simplicity: "too early" last release 2016-07-31

* Devil: OK

* Jarro Negro: OK

* openmamba: no, Italian only -> https://openmamba.org/it/blog/2017/04/26/restart-openmamba/ 
https://openmamba.org/en/downloads/rolling/

**Comment by jorgenatz** [comment]
Turbolinux: A translated version of the page shows that the last desktop product ended support on August 28th, 2015, and the last server product was released on March 13th, 2014. I could not find any user forums, nor other evidence of an active user community beyond the site. 

K12: Under "News Archive", it states that the last release was on March 17th, 2013. I could not find any more recent version of the site in the Internet Archive.

Thank you for looking through the request.

**Comment by FabioLolix** [comment]
* K12: Ok on March 17th, 2013 + 3 years
Missed it at first, in the features is mentioned also:
`K12Linux EL6 is our long-term supported LTSP distribution that will receive updates until the year 2017`
Coincidentally fedorahosted.org was retired on early 2017

* Turbolinux: let's keep it, Turbolinux Appliance Server 4.0 (a virtual machine?) is supported until 2019/03/13
***
* FYI Asianux which is mentioned as old in the readme is still active

**Comment by jorgenatz** [comment]
Should I create a commit with all months in double digits? Many simply have single digits.

**Comment by FabioLolix** [comment]
It is personal quirk I have been doing for new additions, you're not obliged

**Comment by FabioLolix** [comment]
I've added most of things, kept last release date + 1 year for Fedora based distro

Thanks

**Pull request closed without merging**
