### PR TITLE
Update gldt.csv

### PR DESCRIPTION
**Pull request by xingjiapeng**
Rename Deepin to deepin https://www.deepin.org/
Rename Ylmf to Ylmf OS https://distrowatch.com/table.php?distribution=startos
Rename Sparky to Sparkylinux https://sparkylinux.org/
Rename Happy to Happy Linux

### CODE REVIEW

**Comment by xingjiapeng** [comment]
Well...actually Hiweed became Linux Deepin in 2019.12 and became Deepin in 2014.04, then turn to deepin in 2015.04...but I don't know how to fix it.

**Comment by xingjiapeng** [comment]
I tried to update it.

**Comment by xingjiapeng** [comment]
deepin is not based on Morphix any more.
Hiwix 0.1(2004年2月28日) to Hiweed Linux 0.3, it based on Morphix.
Hiweed Linux 0.4(2004年7月22日) to  Hiweed Linux 0.6, it based on Debian.
Hiweed Linux 1.0(2006年9月25日) to  Deepin 2014.3, it based on Ubuntu.
After Deepin 15(2015年12月30日) it based on Debian...

**Comment by xingjiapeng** [comment]
Rename Happy to Happy Linux

**Comment by FabioLolix** [comment]
Hello @xingjiapeng and thank you for your patience

Please squash into a single commit

How you did the changelog [here](https://github.com/FabioLolix/LinuxTimeline/pull/92/commits/530274cee77c6b9f03a44f3d53636614fa57132f) was really fine

In the last days I have started a sort of wiki for Linux/BSD/OpenSolaris distro/OS https://github.com/FabioLolix/Lolix-lists so there is a lot to add

Thank you for information about Deepin, I will make the base jump in the future

**Comment by xingjiapeng** [comment]
> Please squash into a single commit
Sorry... but I don't know how to squash them...
Thanks.

**Comment by FabioLolix** [comment]
Well, you did it for this branch/merge request, which is what I wanted.

I'll update the changelog in the next days

**Comment by FabioLolix** [comment]
> Well...actually Hiweed became Linux Deepin in 2009.12 and became Deepin in 2014.04, then turn to deepin in 2015.04...but I don't know how to fix it.

> deepin is not based on Morphix any more.
Hiwix 0.1(2004年2月28日) to Hiweed Linux 0.3, it based on Morphix.
Hiweed Linux 0.4(2004年7月22日) to Hiweed Linux 0.6, it based on Debian.
Hiweed Linux 1.0(2006年9月25日) to Deepin 2014.3, it based on Ubuntu.
After Deepin 15(2015年12月30日) it based on Debian...

Done 8f7edb7e7921b8eef25813af5a10ebf285ac3341

**Pull request merged**
