### PR TITLE
add Ataraxia Linux

### PR DESCRIPTION
**Pull request by protonesso**
Development started in 2016: https://github.com/ataraxialinux/ataraxia/commit/f06b090dd4eda81f7356f0a99e27c9557d51b4ef
Renamed in 2019: https://github.com/ataraxialinux/ataraxia/commit/2887b4517b3168a6ab091c58169014cbdfa041c1

### CODE REVIEW

**Comment by FabioLolix** [comment]
Hello @protonesso thank you for your patience, I haven't forgot about your distribution

It is passed a long since I first looked at the roadmap and there wasn't yet wget and cmake packaged, I admit I haven't tried it yet

Ataraxia is in the wrong line, it need to be after AsteroidOS

```
"N","OviOS","#000",,"2015.7.13",,,"http://www.ovios.org/",,,,,,,,,
,,,,,,,,,,,,,,,,
"N","Asteroid OS","#e67e22",,"2016.12.7",,,"https://asteroidos.org/",,,,,,,,,
"N","januslinux","#7e7eff",,"2016.12.14",,,"https://ataraxialinux.github.io/","Ataraxia Linux","2019.04.10",,,,,,,,,
,,,,,,,,,,,,,,,
```

In the last days I have started a sort of wiki for Linux/BSD/OpenSolaris distro/OS https://github.com/FabioLolix/Lolix-lists

There is need for filling for Ataraxia

https://github.com/FabioLolix/Lolix-lists/blob/master/os/linux/a/ataraxia.md

https://raw.githubusercontent.com/FabioLolix/Lolix-lists/master/os/linux/a/ataraxia.md

**Comment by protonesso** [comment]
I will work on it tomorrow!

**Comment by protonesso** [comment]
I will do new pull request because can't change commits

**Comment by protonesso** [comment]
oops i noticed my branch

**Comment by protonesso** [comment]
fixed!

**Comment by FabioLolix** [comment]
as I have asked to other; please squash into a single commit

**Comment by protonesso** [comment]
okay

**Pull request closed without merging**
